### ISSUE TITLE
YesPlayMusic

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#11]
A 3rd Party player of NeteaseCloudMusic.
https://github.com/qier222/YesPlayMusic
![32AE326D-6FF0-4F24-A5CC-174AF79B7608](https://user-images.githubusercontent.com/42692274/119173908-7b391300-ba9a-11eb-8efe-7e5367a294c8.png)
![3B8FAF18-3B12-46A2-B2CE-B4F3F91D0C67](https://user-images.githubusercontent.com/42692274/119173921-7f653080-ba9a-11eb-8f4f-58afb7563585.png)

https://github.com/qier222/YesPlayMusic/releases/download/v0.3.8/yesplaymusic_0.3.8_armv7l.deb
armv7 is supported.

**Comment by chunky-milk** [comment]
Added. Thanks for the suggestion.
