### ISSUE TITLE
CherryTree

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#12]
A hierarchical note taking application, featuring rich text and syntax highlighting, storing data in a single XML or SQLite file. 
https://github.com/giuspen/cherrytree
https://launchpad.net/~giuspen/+archive/ubuntu/ppa/+packages
Officially only arm64 is supported. If we want to support armhf, we need to compile it ourselves.

**Comment by chunky-milk** [comment]
Added. Thanks for the suggesstion
