### ISSUE TITLE
macintosh.js

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#14]
https://github.com/felixrieseberg/macintosh.js
 A virtual Apple Macintosh with System 8, running in Electron. 
 https://github.com/felixrieseberg/macintosh.js/releases/tag/v1.1.0
Armhf and arm64 deb packages are available in the latest version.
![DAAAA1BD-40D0-451F-B7FE-07A7D7DBC2E3](https://user-images.githubusercontent.com/42692274/119184248-b8f06880-baa7-11eb-95c7-4a41124556ce.jpeg)

**Comment by chunky-milk** [comment]
Added to osdn mirror.
