### ISSUE TITLE
Tabby (formerly Terminus)

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#15]
A terminal for a more modern age
https://github.com/Eugeny/tabby
![image](https://user-images.githubusercontent.com/42692274/128796220-5c9069b9-6d4f-452b-b382-bdc4ba455511.png)
https://github.com/Eugeny/terminus/releases/download/v1.0.139/terminus-1.0.139-linux.deb
I don’t know if the deb package supports arm.

**Comment by chunky-milk** [comment]
Unfortunately, the deb you provided only supports the `amd64` architecture. I will attempt to compile the software

**Comment by hmsjy2017** [comment]
I have successfully compiled its arm64 version.
https://github.com/hmsjy2017/tabby/releases/tag/v1.0.153-nightly

**Comment by chunky-milk** [comment]
Added, closing now.
