### ISSUE TITLE
ctop

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#16]
Top-like interface for container metrics
https://github.com/bcicen/ctop
Deb packages are there: 
http://packages.azlux.fr/debian/pool/main/d/docker-ctop/

![A91A6C53-CD15-4E8D-98A0-8588B4D6AFFB](https://user-images.githubusercontent.com/42692274/119536997-34aa2800-bdbc-11eb-9d07-de1e37d38360.gif)

**Comment by chunky-milk** [comment]
Added
