### ISSUE TITLE
How did you compile rpi-play

### ISSUE THREAD

**Issue by CleanMachine1** [chunky-milk/raspbian-addons#2]
I am sure @Botspot will use your deb after I gave said I have given up, how did you compile with checkinstall, mine gives cmake errors because of arm and blah blah blah

**Comment by Itai-Nelken** [comment]
How did you use checkinstall? It shouldn't give any arch errors.
You should run the `cmake` line, then the `make` line and then instead of `make install`, `checkinstall sudo make install`
Change the command after checkinstall to the correct installation command, the default its make install.

**Comment by CleanMachine1** [comment]
Yes thats how i did it

**Comment by chunky-milk** [comment]
> Yes thats how i did it

Did you compile on a Pi, or on an x86 Linux machine?

**Comment by CleanMachine1** [comment]
Pi on rpi os

**Comment by CleanMachine1** [comment]
The arm error just seemed to be an issue with checksum using arm cmake

Copying the error gave some other guy on a pi getting the same error, he was compiling opencv on arm

**Comment by CleanMachine1** [comment]
hmm, I just checked again and using the checkinstall sudo make install worked..
I was using sudo checkinstall make install
