### ISSUE TITLE
logo-ls

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#22]
modern ls command with beautiful Icons and Git Integrations . Written in Golang
https://github.com/Yash-Handa/logo-ls
![F671E6D7-852E-4610-A898-76FD6C49C89E](https://user-images.githubusercontent.com/42692274/120520481-6ba8bb00-c406-11eb-9cb7-abb6ae0e75c7.png)
Armv6 and arm64 deb packages are provided.
https://github.com/Yash-Handa/logo-ls/releases/tag/v1.3.7

**Comment by Itai-Nelken** [comment]
There is also 'exa' that also looks nice and has git integration

**Comment by chunky-milk** [comment]
I have added it. will close when it syncs

**Comment by chunky-milk** [comment]
It should be there now.
