### ISSUE TITLE
broot

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#23]
A better way to navigate directories
https://github.com/Canop/broot
![1E415D08-4C2C-439C-A6F7-D928278B967A](https://user-images.githubusercontent.com/42692274/120521160-33ee4300-c407-11eb-9a23-d5702d6ea386.png)
![A1DC4115-6381-4800-9375-AAD6BE120BE0](https://user-images.githubusercontent.com/42692274/120521168-35b80680-c407-11eb-8acf-90a94f8ef5e8.png)
Deb packages compatible with armhf can be found here.
https://packages.azlux.fr/debian/pool/main/b/broot/

**Comment by chunky-milk** [comment]
I have added it. @hmsjy2017 just so you know i use `cron` to sync the files on OSDN at 1 AM in the morning (eastern). So the changes won't appear until then. I'll close this when it syncs

**Comment by chunky-milk** [comment]
Added
