### ISSUE TITLE
Add CDN link for installation script

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#28]
The domain names of git.io and raw.githubusercontent.com cannot be accessed in Chinese mainland. So I think the CDN link of the script can be used: https://cdn.jsdelivr.net/gh/chunky-milk/raspbian-addons@master/repo.sh

**Comment by chunky-milk** [comment]
Thanks for letting me know, added with [this commit](https://github.com/chunky-milk/raspbian-addons/commit/664bfff4848891ad6cadbc6e440464d23f6f1519)
