### ISSUE TITLE
Ulauncher

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#29]
Linux Application Launcher
https://github.com/Ulauncher/Ulauncher

Licensing: GPL-3.0

![C8E15650-AEC6-43FE-B06E-0A730738169D](https://user-images.githubusercontent.com/42692274/120830573-37add100-c591-11eb-974a-7fbe3a176470.png)

Packages:
 Stable release:  https://github.com/Ulauncher/Ulauncher/releases/download/5.11.0/ulauncher_5.11.0_all.deb

 Dev release: 
https://github.com/Ulauncher/Ulauncher/releases/download/5.11.0-beta1/ulauncher_5.11.0.beta1_all.deb

**Comment by hmsjy2017** [comment]
@chunky-milk But it’s beta version is not there.

**Comment by chunky-milk** [comment]
> @chunky-milk But it’s beta version is not there.

I'd like to stick with the stable release for now. anyways I cannot add the stable *and* beta release, because they have the same package name
