### ISSUE TITLE
tut

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#30]
A TUI for Mastodon with vim inspired keys.
https://github.com/RasmusLindroth/tut

Licensing: MIT

![2EDB6274-C1DE-4FDC-8360-74DD7435D2A9](https://user-images.githubusercontent.com/42692274/120831911-a2134100-c592-11eb-9dbc-6eeec3847d04.png)
Packages：https://packages.azlux.fr/debian/pool/main/t/tut/

**Comment by chunky-milk** [comment]
Should be in the repo now.
