### ISSUE TITLE
webhookd

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#31]
A very simple webhook server launching shell scripts.
https://github.com/ncarlier/webhookd

Licensing: MIT
![B0A6416D-3D69-431A-B2AC-044C6B93E125](https://user-images.githubusercontent.com/42692274/120832189-f3bbcb80-c592-11eb-9332-1747be976d54.gif)

Packages：https://packages.azlux.fr/debian/pool/main/w/webhookd/

**Comment by chunky-milk** [comment]
There was an error during the last sync, I'll attempt to fix it soon

**Comment by chunky-milk** [comment]
Fixed the error. Added now
