### ISSUE TITLE
Syncthing-GTK

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#34]
GTK3 & python based GUI for Syncthing
https://github.com/kozec/syncthing-gtk
![E54D9FC9-636B-432B-A2E6-4010E82900D3](https://user-images.githubusercontent.com/42692274/120851218-1bb72900-c5ab-11eb-9f3f-47c6b6a5d9c1.png)

Licensing: GPL-2.0

Packages:
http://download.opensuse.org/repositories/home:/kozec/Debian_10/armhf/syncthing-gtk_0.9.4.4-1_armhf.deb
http://download.opensuse.org/repositories/home:/kozec/Debian_10/arm64/syncthing-gtk_0.9.4.4-1_arm64.deb

**Comment by chunky-milk** [comment]
Added
