### ISSUE TITLE
Syncthing

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#35]
Open Source Continuous File Synchronization

Licensing:  MPL-2.0

Packages:
https://apt.syncthing.net/dists/syncthing/stable/binary-armhf/syncthing_1.17.0_armhf.deb
https://apt.syncthing.net/dists/syncthing/stable/binary-arm64/syncthing_1.17.0_arm64.deb

https://github.com/syncthing/discosrv/releases/download/v1.8.0/syncthing-discosrv_1.8.0_armhf.deb
https://github.com/syncthing/discosrv/releases/download/v1.8.0/syncthing-discosrv_1.8.0_arm64.deb

https://github.com/syncthing/relaysrv/releases/download/v1.15.0/syncthing-relaysrv_1.15.0_armhf.deb
https://github.com/syncthing/relaysrv/releases/download/v1.15.0/syncthing-relaysrv_1.15.0_arm64.deb

**Comment by chunky-milk** [comment]
Added all the packages
