### ISSUE TITLE
croc

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#36]
Easily and securely send things from one computer to another
https://github.com/schollz/croc

Licensing:MIT
![0FF7E2FB-8ACE-43E2-A7C5-7AA128D09C5D](https://user-images.githubusercontent.com/42692274/120885942-1b0baa80-c61e-11eb-9067-25712da2bdea.gif)

Packages: https://github.com/schollz/croc/releases/tag/v9.1.4

**Comment by chunky-milk** [comment]
added
