### ISSUE TITLE
ArchiveBox

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#38]
Open-source self-hosted web archiving.
https://github.com/ArchiveBox/ArchiveBox

Licensing:MIT
![384105BB-07F4-4FF3-A8FF-84AA8731D514](https://user-images.githubusercontent.com/42692274/120922779-a7d96580-c6fd-11eb-921a-d25c70c36b6b.png)

Packages: https://github.com/ArchiveBox/ArchiveBox/releases/tag/v0.6.2

**Comment by chunky-milk** [comment]
Will be uploaded in the next sync.
