### ISSUE TITLE
The latest Firefox browser and its language packs

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#39]
The Firefox browser version in the official Raspbian repository is relatively old. The latest version is available in the experimental distribution of the Debian repository and the Ubuntu Ports repository. I don't know if the Firefox browser in Ubuntu Ports is suitable for Raspberry Pi.

Licensing: MPL

Packages: 
https://packages.debian.org/experimental/firefox
http://ports.ubuntu.com/ubuntu-ports/pool/main/f/firefox/

**Comment by Itai-Nelken** [comment]
Its possible to install it from the Ubuntu ports (see https://www.github.com/chunky-milk/pi-bashscripts-files/tree/main/Firefox.md) but in my testing it's very unstable and vrashes frequently especially after signing in.

**Comment by chunky-milk** [comment]
> Its possible to install it from the Ubuntu ports (see https://www.github.com/chunky-milk/pi-bashscripts-files/tree/main/Firefox.md) but in my testing it's very unstable and crashes frequently especially after signing in.

Also, websites seem to recognize it as a mobile browser, not as a desktop...

**Comment by Itai-Nelken** [comment]
That can be changed easily:
1. Find the user agent of Firefox.
2. Search how to change it, its really easy but I don't remember how.
3. Restart it

**Comment by chunky-milk** [comment]
Added.

**Comment by hmsjy2017** [comment]
@chunky-milk Could you add the firefox-locale-zh-hans package? I want to use its Chinese version.
http://ports.ubuntu.com/ubuntu-ports/pool/main/f/firefox/firefox-locale-zh-hans_89.0+build2-0ubuntu0.21.04.1_arm64.deb
http://ports.ubuntu.com/ubuntu-ports/pool/main/f/firefox/firefox-locale-zh-hans_89.0+build2-0ubuntu0.21.04.1_armhf.deb
