### ISSUE TITLE
WebTorrent Desktop 

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#40]
Streaming torrent app for Mac, Windows, and Linux
https://github.com/webtorrent/webtorrent-desktop

Licensing: MIT
![60E40109-3EA4-45F1-A1EC-B8975BF79D7C](https://user-images.githubusercontent.com/42692274/120986263-fabf2580-c7ae-11eb-90fa-ad3dbede1cb0.png)

Packages: https://github.com/webtorrent/webtorrent-desktop/releases/tag/v0.24.0
(Only arm64 version is provided.)

**Comment by chunky-milk** [comment]
Added
