### ISSUE TITLE
warpinator

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#41]
Share files across the LAN
https://github.com/linuxmint/warpinator

Licensing: GPL-v3.0

I have compiled a deb package.
https://github.com/hmsjy2017/warpinator/releases/tag/1.2.0
****
Edited: 
I found it in the Linux Mint repository.
http://packages.linuxmint.com/pool/backport/w/warpinator/
****
It is easy to compile, and the compiled deb package is suitable for any architecture. So I plan to use GitHub Actions to automatically compile it.

There may be some problems when installing it. Therefore, we need to use `sudo apt-get install -f` to resolve installation dependencies.

I want to know if it is possible to automatically install dependencies when installing it instead of manually installing it.

In addition, I think more programs written in python can be packaged into deb packages to install them easily.

**Comment by chunky-milk** [comment]
Added, to install it run `sudo apt update` and then `sudo apt-get install warpinator`, and the dependencies should automatically install also.
