### ISSUE TITLE
GoReleaser

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#42]
Deliver Go binaries as fast and easily as possible.
https://github.com/goreleaser/goreleaser

Licensing: MIT

Packages: https://github.com/goreleaser/goreleaser/releases

We can use it to package programs written in Golang into debs to easily distribute them.
In addition, the project provides templates for GitHub Actions. We can easily use it to automatically compile software.
https://github.com/goreleaser/goreleaser-action

**Comment by chunky-milk** [comment]
Added. I'll work on the github actions in my [autobuild repo](https://github.com/chunky-milk/autobuildservice)
