### ISSUE TITLE
AdoptOpenJDK

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#43]
Prebuilt OpenJDK Binaries for Free
https://adoptopenjdk.net/

Licensing:

Build scripts and other code to produce the binaries, the website and other build infrastructure are licensed under [Apache License](https://www.apache.org/licenses/LICENSE-2.0), Version 2.0.
OpenJDK code itself is licensed under [GPL v2 with Classpath Exception (GPLv2+CE)](https://openjdk.java.net/legal/gplv2+ce.html).
Eclipse OpenJ9 is licensed under [Several licenses](https://github.com/eclipse/openj9/blob/master/LICENSE).

Packages: 
Release: https://adoptopenjdk.jfrog.io/artifactory/deb/pool/main/a/
Nightly: https://adoptopenjdk.jfrog.io/artifactory/deb-nightly/pool/main/a/
A lot of versions are provided.

**Comment by chunky-milk** [comment]
Which package from there would you like me to add?

**Comment by chunky-milk** [comment]
There is a more up-to-date version, which is `adoptopenjdk-16-hotspot-jre`, would you like me to add that one instead?

**Comment by chunky-milk** [comment]
I added all the adoptopenjdk-16 packages. Some are only for arm64.
