### ISSUE TITLE
Caddy

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#46]
Caddy 2 is a powerful, enterprise-ready, open source web server with automatic HTTPS written in Go
https://github.com/caddyserver/caddy

Licensing:  Apache-2.0

Packages: 
https://github.com/caddyserver/caddy/releases
And
https://github.com/caddyserver/xcaddy/releases
(The xcaddy command is the easiest way to build Caddy with version information and/or plugins.)

The deb packages can also be found here:
https://cloudsmith.io/~caddy/repos/

**Comment by chunky-milk** [comment]
Added
