### ISSUE TITLE
hypnotix

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#47]
An M3U IPTV Player
https://github.com/linuxmint/hypnotix

Licensing: GPLv3
![658E71F6-C64D-4CD9-9A2E-4AE7CAD720E3](https://user-images.githubusercontent.com/42692274/121336900-891ddd80-c94e-11eb-8ba7-0791f791401a.png)

Packages: https://github.com/linuxmint/hypnotix/releases/tag/1.1

**Comment by chunky-milk** [comment]
Added
