### ISSUE TITLE
Deskreen

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#48]
Deskreen turns any device with a web browser into a secondary screen for your computer
https://github.com/pavlobu/deskreen

Licensing: AGPL-3.0 
![4FD92768-14EA-4ECC-9892-5DF41571E7FF](https://user-images.githubusercontent.com/42692274/121391258-c00ce700-c980-11eb-8d35-86ca25fd05e0.jpeg)

Packages: https://github.com/hmsjy2017/deskreen/releases/tag/v1.0.11

I think it can add to automatic compilation.

It is very easy to build.
Just edit https://github.com/pavlobu/deskreen/blob/e9bd0ef6cdcfd644c4fe5d576f64dfa9b2c1c45f/package.json#L28

### armhf 
```
"package": "yarn build && electron-builder build --armv7l --publish never",
```
### arm64 
```
"package": "yarn build && electron-builder build --arm64 --publish never",
```
Then run `cd app/client; yarn install --frozen-lockfile ; cd ../../ ; yarn install --frozen-lockfile` and `yarn package` -- to package an app and make executables available in `release` folder.

**Comment by chunky-milk** [comment]
Added
