### ISSUE TITLE
Bulky

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#50]
Bulky is used to rename files and directories.
https://github.com/linuxmint/bulky
![BB59DDE3-B69C-4D00-BFA9-18DE9E4562C3](https://user-images.githubusercontent.com/42692274/121553599-fcede200-ca43-11eb-8a7a-48dce7fec57f.png)

Licensing: GPLv3

Packages: http://packages.linuxmint.com/pool/main/b/bulky/

**Comment by chunky-milk** [comment]
Added
