### ISSUE TITLE
The latest version of Python 3

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#52]
Python 3 in Debian buster still stays at version 3.7, but the latest stable version is 3.9.5.
The latest beta version is 3.10.0b2.

Licensing: https://github.com/python/cpython/blob/main/LICENSE

Packages: 
Stable: https://packages.debian.org/experimental/python3.9
Testing: https://packages.debian.org/experimental/python3.10

**Comment by chunky-milk** [comment]
I'm adding the latest stable version, but it seems like there are a lot of dependencies. Could you let me know if it installs successfully on your system? (after the mirror sync of course)

**Comment by hmsjy2017** [comment]
There is something wrong with the network connection of my Raspberry Pi. But I am busy preparing for the final exam and have no time to deal with it. I’m sorry.

**Comment by hmsjy2017** [comment]
@chunky-milk I tried to install it, but it failed due to dependency issues.

**Comment by chunky-milk** [comment]
> @chunky-milk I tried to install it, but it failed due to dependency issues.

That's what I was afraid of :(

Since the python packages require a newer version of libc6 and others, they have so many dependencies it just doesn't make sense to add it unless I am adding the whole repository.

**Comment by hmsjy2017** [comment]
@chunky-milk I suggest you remove it from the repository. Because it cannot be installed normally and the maintenance is too difficult.

**Comment by chunky-milk** [comment]
> @chunky-milk I suggest you to remove it from the repository. Because it cannot be installed normally and the maintenance is too difficult.

I will.

**Comment by hmsjy2017** [comment]
Closed.
