### ISSUE TITLE
Update drawing

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#53]
v0.8.1
https://launchpad.net/~cartes/+archive/ubuntu/drawing/+files/drawing_0.8.1-0ubuntu1~hirsute_arm64.deb
https://launchpad.net/~cartes/+archive/ubuntu/drawing/+files/drawing_0.8.1-0ubuntu1~hirsute_armhf.deb

**Comment by chunky-milk** [comment]
Thanks for reminding me
