### ISSUE TITLE
Update bpytop 1.0.66 --> 1.0.67

### ISSUE THREAD

**Issue by Itai-Nelken** [chunky-milk/raspbian-addons#55]
here is a deb I created. its based on the old deb that is currently in the repo, but I bumped the version in the control file and updated the python script itself.
[bpytop_1.0.67_all.deb.zip](https://github.com/chunky-milk/raspbian-addons/files/6687590/bpytop_1.0.67_all.deb.zip)

**Comment by chunky-milk** [comment]
Added
