### ISSUE TITLE
SoftEtherVPN

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#59]
An Open-Source Cross-platform Multi-protocol VPN Program
https://github.com/SoftEtherVPN/SoftEtherVPN

Licensing: Apache

Packages: 
The packages can be downloaded from PPA: https://launchpad.net/~paskal-07/+archive/ubuntu/softethervpn

The latest version: https://launchpad.net/~paskal-07/+archive/ubuntu/softethervpn/+sourcepub/12449833/+listing-archive-extra

**softether-common** SoftEther VPN is an open-source cross-platform multi-protocol VPN program, created as an academic project in the University of Tsukuba.
**softether-vpnbridge** VPN Bridge daemon
**softether-vpnclient** VPN Client daemon
**softether-vpncmd** Command line utils
**softether-vpnserver** VPN Server daemon

**Comment by chunky-milk** [comment]
I added it, try installing. If there are any dependency issues just let me know and I can try to fix them
