### ISSUE TITLE
code-server

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#60]
https://github.com/cdr/code-server
VS Code in the browser
<img width="1202" alt="CA1541AE-0AD8-43F8-B201-7E3BFFF86A99" src="https://user-images.githubusercontent.com/42692274/126052191-f89eb00a-b003-4c26-a1d8-2b02cb701c24.png">

## Highlights
- Code on any device with a consistent development environment
- Use cloud servers to speed up tests, compilations, downloads, and more
- Preserve battery life when you're on the go; all intensive tasks run on your server

Licensing: MIT

Packages: https://github.com/cdr/code-server/releases

**Comment by chunky-milk** [comment]
Wow this is a really cool project! I'll add it into the next sync

**Comment by hmsjy2017** [comment]
Closed.
