### ISSUE TITLE
Add pbgopy

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#7]
pbgopy acts like pbcopy/pbpaste but for multiple devices. It lets you share data across devices like you copy and paste.
https://github.com/nakabonne/pbgopy
![BAE417AE-A4ED-44DB-9149-23CE4E13B4DA](https://user-images.githubusercontent.com/42692274/118681081-e0d69680-b831-11eb-9bab-9c042c2592df.gif)

**Comment by chunky-milk** [comment]
Done. Thanks for letting me know.
