### ISSUE TITLE
Issue wuth repo.py

### ISSUE THREAD

**Issue by Itai-Nelken** [chunky-milk/raspbian-addons#74]
https://github.com/chunky-milk/raspbian-addons/blob/f5f5bea2262236c207bc8bbc232fb9a072bfe640/repo.py#L47 
The error function is not defined, do if `apt update` fails, the dhell will error. 
I will fix it tomorrow if it isn't fixed until then.

**Comment by Itai-Nelken** [comment]
done

**Comment by chunky-milk** [comment]
Thanks for catching this 😀
