### ISSUE TITLE
Update gh & v2raya

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#75]
gh v1.14.0
https://github.com/cli/cli/releases/tag/v1.14.0
v2rayA v1.4.3
https://github.com/v2rayA/v2rayA/releases/tag/v1.4.4

**Comment by chunky-milk** [comment]
I'll update them as soon as I can.

**Comment by hmsjy2017** [comment]
@chunky-milk I think it might be possible to write a script to automatically update the packages. So that we can ensure that the packages are always at the latest version.

**Comment by chunky-milk** [comment]
> @chunky-milk I think it might be possible to write a script to automatically update the packages. So that we can ensure that the packages are always at the latest version.

I'm working on it

**Comment by chunky-milk** [comment]
Later today, I'm planning to run a mirror sync to update some of the packages

**Comment by chunky-milk** [comment]
updated
