### ISSUE TITLE
Add SysMonTask

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#77]
https://github.com/KrispyCamel4u/SysMonTask
Linux system monitor with the compactness and usefulness of Windows Task Manager to allow higher control and monitoring.
![F914FC09-3607-42C1-97E4-4D76EEECB9BD](https://user-images.githubusercontent.com/42692274/129772977-45b6a6e1-a72d-4912-a1de-e3498c196cb9.png)

Licensing:  BSD-3-Clause 

Packages: https://github.com/KrispyCamel4u/SysMonTask/releases

**Comment by chunky-milk** [comment]
SysMonTask is already in the repo
