### ISSUE TITLE
Add OpenCV

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#78]
https://github.com/opencv/opencv
Open Source Computer Vision Library

Licensing: Apache

arm64(v4.5.1): https://github.com/hmsjy2017/debian-pi-aarch64-apps/releases/tag/v4.5.1
armhf(v4.5.0): https://github.com/cyysky/OpenCV-Raspberry-Pi-4-Package-for-Python/releases/tag/4.5.0

**Comment by chunky-milk** [comment]
added
