### ISSUE TITLE
Add rclone

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#8]
https://github.com/rclone/rclone

Rclone ("rsync for cloud storage") is a command line program to sync files and directories to and from different cloud storage providers.

**Comment by chunky-milk** [comment]
Added. Thanks for the suggestion.

**Comment by hmsjy2017** [comment]
Please add its beta version:
https://packages.azlux.fr/debian/pool/main/r/rclone/
