### ISSUE TITLE
Source Han Serif

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#80]
https://github.com/adobe-fonts/source-han-serif
Source Han Serif is a set of OpenType/CFF Pan-CJK fonts.

Licensing:OFL-1.1

Packages: https://github.com/hmsjy2017/fonts/releases

zh_CN: https://github.com/hmsjy2017/fonts/releases/download/source-han-serif-v1.001/source-han-serif-cn_1.001_all.deb
zh_TW: https://github.com/hmsjy2017/fonts/releases/download/source-han-serif-v1.001/source-han-serif-tw_1.001_all.deb

They can be successfully installed and can be recognized in WPS Office.

**Comment by chunky-milk** [comment]
Added.
