### ISSUE TITLE
Elasticsearch

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#84]
https://github.com/elastic/elasticsearch
Free and Open, Distributed, RESTful Search Engine

Licensing: [Elastic License 2.0](https://github.com/elastic/elasticsearch/tree/7.14/licenses/ELASTIC-LICENSE-2.0.txt)

Packages: https://www.elastic.co/downloads/elasticsearch
https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.14.0-arm64.deb

Install with Debian Package
https://www.elastic.co/guide/en/elasticsearch/reference/7.14/deb.html

**Comment by chunky-milk** [comment]
Added
