### ISSUE TITLE
Corretto

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#85]
https://aws.amazon.com/corretto/
Amazon Corretto is a no-cost, multiplatform, production-ready distribution of the Open Java Development Kit (OpenJDK).

Licensing: GPL-2.0

Packages: 
https://corretto.aws/downloads/latest/amazon-corretto-8-aarch64-linux-jdk.deb
https://corretto.aws/downloads/latest/amazon-corretto-11-aarch64-linux-jdk.deb
https://corretto.aws/downloads/latest/amazon-corretto-16-aarch64-linux-jdk.deb

Docs:
https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/generic-linux-install.html
https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/generic-linux-install.html
https://docs.aws.amazon.com/corretto/latest/corretto-16-ug/generic-linux-install.html

**Comment by chunky-milk** [comment]
Added
