### ISSUE TITLE
Jenkins

### ISSUE THREAD

**Issue by hmsjy2017** [chunky-milk/raspbian-addons#86]
https://github.com/jenkinsci/jenkins
Jenkins is an open source continuous integration (CI) tool that provides a friendly operation interface.  It is mainly used for continuous and automatic construction/testing of software projects and monitoring the operation of external tasks.

Licensing: MIT

Packages: https://github.com/jenkinsci/jenkins/releases
https://pkg.jenkins.io/debian-stable/

**Comment by chunky-milk** [comment]
Added
